version: "3.9"

services:
  postgres_db:
    image: test_postgres
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - app
  application:
    image: test_app
    container_name: service_a
    ports:
      - "8080:8080"
    env_file:
      - ../env-files/.env.dev
    networks:
      - app

networks:
  app:
    name: app_network